name: device-manager
services:
  api:
    build:
      context: ..
      dockerfile: docker-config/Dockerfile
    container_name: device-api
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__Default: "Server=db,1433;Database=DeviceManager;User Id=sa;Password=${SQL_SA_PASSWORD};TrustServerCertificate=True;Encrypt=False"
    ports:
      - "8080:8080"
