name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main   # también escuchamos main, pero diferenciamos en jobs/steps

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build & Push Docker image (develop)
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: b4c0c6w7/tesis/tp1-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f docker-config/Dockerfile -t $REGISTRY/$REPOSITORY:develop-$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:develop-$IMAGE_TAG

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build & Push Docker image (main)
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: b4c0c6w7/tesis/tp1-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f docker-config/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
